# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionCalculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.AddField(
            model_name='food',
            name='allergen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
    ]
